version: '3.8'

services:
  postgres:
    image: postgres:alpine3.22
    container_name: lab-crm-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crm_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  order-crm-service:
    container_name: order-crm-service
    build:
      context: .
      dockerfile: Dockerfile
    image: order-crm
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - .env
volumes:
  postgres_data: